apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2023-05-22T03:00:51Z"
  name: serviceaccounts-cluster-admin
  resourceVersion: "42710"
  uid: be78306a-18dd-4920-877e-e40acd2192a4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
