apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
spec:
  gateways:
  - knative-serving/front-backend-gateway
  hosts:
  - {{ .Values.domain }}
  http:
  - route:
    - destination:
        host: frontend.default.svc.cluster.local
  tls:
  - match:
    - port: 443
      sniHosts:
      - {{ .Values.domain }}
    route:
    - destination:
        host: frontend.default.svc.cluster.local
        port:
          number: 443
