apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: 'dennisfaut/elonwallet-frontend-sgx'
          ports:
          - containerPort: 443
          volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /dev/sgx/enclave
            name: dev-sgx-enclave
          - mountPath: /dev/sgx_enclave
            name: dev-sgx-enclave
          - mountPath: /dev/sgx_provision
            name: dev-sgx-provision
      volumes:
      - name: dev-sgx-provision
        hostPath:
          path: /dev/sgx_provision
      - name: dev-sgx-enclave
        hostPath:
          path: /dev/sgx_enclave
      - name: data
        hostPath:
          path: /etc/frontend/data
